version: '2'
services:
  db:
    build: db
    #entrypoint: ["pg_restore", "-c", "-d", "bigg", "/src/bigg_database.dump"]
    #command: ["pg_restore", "-c", "-d", "bigg", "/src/bigg_database.dump"]

    environment:
      - DEBUG=false

      - DB_USER=postgres
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
  web:
    build: web
    environment:
      - PROCESSES=6
    entrypoint: ["/src/wait-for-it.sh", "db:5432", "-t", "120", "--", "/src/init.sh"]
    ports:
      - "127.0.0.1:8910:8910"
    depends_on:
      - db
    links:
      - db:db
 