# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEVELOPMENT
# -----------------------------------------------------------------------------
version: '3'

volumes:
  adb_data:
    driver: local

services:
  adb:
    restart: always
    image: postgres:11.2
    ports:
      - "5434:5432"
    volumes:
      - adb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=adb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adb
