# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEVELOPMENT
# -----------------------------------------------------------------------------
version: '3'

volumes:
  django_static:
    driver: local
  django_media:
    driver: local
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  bigg_data:
    driver: local


services:

  postgres:
    restart: always
    image: postgres:11.2
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bigg:
    restart: always
    image: postgres:11.2
    ports:
      - "5435:5432"
    volumes:
      - bigg_data:/var/lib/postgresql/data


  elasticsearch:
    restart: always
    image: elasticsearch:6.7.1
    ports:
      - "9124:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    env_file: .env.local
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
    depends_on:
     - postgres
     - elasticsearch
    command: bash -c "/usr/local/bin/python manage.py runserver 0.0.0.0:9000"
