# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEVELOPMENT
# -----------------------------------------------------------------------------
version: '3'

volumes:
  django_static:
    driver: local
  django_media:
    driver: local
  adb_data:
    driver: local
  elasticsearch_data:
    driver: local
  vue_dist:
    driver: local
  node_modules:
    driver: local

networks:
  adbnet:


services:
  adb:
    restart: always
    container_name: adb_postgres
    build: ./adb
    ports:
      - "5434:5432"
    volumes:
      - adb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ADB_DB_NAME}
      - POSTGRES_USER=${ADB_DB_USER}
      - POSTGRES_PASSWORD=${ADB_DB_PASSWORD}
    networks:
      - adbnet

  elasticsearch:
    restart: always
    container_name: adb_elasticsearch
    image: elasticsearch:6.8.1
    ports:
      - "9124:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - adbnet

  kibana:
    image: kibana:6.8.1
    container_name: adb_kibana
    ports:
      - "5610:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - adbnet
    depends_on:
      - elasticsearch

  backend:
    restart: always
    container_name: adb_backend
    build: ./backend
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    env_file: .env.local
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - adb:adb
      - elasticsearch:elasticsearch
    depends_on:
     - adb
     - elasticsearch
    command: bash -c "/usr/local/bin/python manage.py runserver 0.0.0.0:9000"
    networks:
      - adbnet

  frontend:
    restart: always
    container_name: adb_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-develop
    ports:
      - "8090:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/
      - vue_dist:/usr/share/nginx/html
    networks:
      - adbnet
