# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEVELOPMENT
# -----------------------------------------------------------------------------
version: '3'

volumes:
  django_static:
    driver: local
  django_media:
    driver: local
  adb_data:
    driver: local
  elasticsearch_data:
    driver: local
  vue_dist:
    driver: local
  node_modules:
    driver: local

networks:
  adbnet:


services:
  adb:
    restart: always
    container_name: adb_postgres
    build: ./adb
    ports:
      - "5434:5432"
    volumes:
      - adb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ADB_DB_NAME}
      - POSTGRES_USER=${ADB_DB_USER}
      - POSTGRES_PASSWORD=${ADB_DB_PASSWORD}
    networks:
      - adbnet

  elasticsearch:
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.name=adb_elasticsearch
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: adb_elasticsearch
    image: elasticsearch:7.7.1
    ports:
      - "9124:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - adbnet

  backend:
    restart: always
    container_name: adb_backend
    build: ./backend
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    env_file: .env.production
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - adb:adb
      - elasticsearch:elasticsearch
    depends_on:
     - adb
     - elasticsearch
    command: bash -c "/usr/local/bin/gunicorn adb_app.wsgi:application --log-config gunicorn_logging.conf -w 4 --bind 0.0.0.0:9000"
    networks:
      - adbnet

  frontend:
    container_name: adb_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-production
    command: tail -f /dev/null
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/
      - vue_dist:/vue

  nginx:
    container_name: adb_nginx
    restart: always
    image: nginx:1.18.0
    ports:
      - 8889:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - django_static:/static
      - django_media:/media
      - vue_dist:/vue
    depends_on:
      - backend
      - frontend
    links:
      - backend:backend
    networks:
      - adbnet